Adds new asset metadata page
Screenly/playground pull request #30
Opened 2022-05-20 17:33 UTC by iamplugged

Specs: https://www.figma.com/file/U0awkNQKLDKmOP7k9xiZUQ/WA-Review?node-id=3211%3A18701

Implementation:
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/6959733/169581834-702e1860-5ba1-4c1f-8f65-6ee80b3b0040.png">

2022-05-21 07:16 UTC, vpetersson commented
Great stuff, @iamplugged!

2022-05-21 07:21 UTC, vpetersson requested changes
Minor change, but we also need to add fallbacks if the headers are unavailable.

2022-05-21 07:21 UTC, vpetersson commented on asset-metadata/src/templates/metadata_headers.html
> +            <label>Host name:</label>
Should be "Hostname"

2022-05-22 04:27 UTC, iamplugged commented on asset-metadata/src/templates/metadata_headers.html
> +            <label>Host name:</label>
Changes done

2022-05-27 14:28 UTC, vpetersson approved these changes

2022-05-27 14:28 UTC, merged