Adds: documentation on web asset metadata
Screenly/playground pull request #5
Opened 2022-03-29 15:38 UTC by korvyashka

2022-03-29 15:42 UTC, vpetersson requested changes
Please add `requirements.txt` and a `Dockerfile` to package this up in. Maybe cleaner if you just use Flask or something instead as I want to build this out a bit and style it.

2022-03-30 19:24 UTC, sergey-borovkov commented on asset-metadata/README.md
> +like hostname, screen name, location, etc.
No need for etc. here. We have a full list of headers we expose. Should list all of them.

2022-03-30 19:25 UTC, sergey-borovkov commented on asset-metadata/README.md
> +Example headers
Example header values? not sure, just need to make sure people understand that the list of headers is complete. But values are an example

2022-03-31 07:13 UTC, sergey-borovkov commented on asset-metadata/README.md
> +To enable on asset click 'Advanced' on any web asset
To enable sending of metadata 
Or something like that

2022-03-31 07:18 UTC, sergey-borovkov approved these changes

2022-03-31 08:21 UTC, merged